### PR TITLE
[IMP] Allow to ignore some modules to avoid warning

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@sebastienbeau @simahawk @sbidoul 

This is a simple (too ?) way of getting rid of :

image


As Odoo core module (mail in this case) import some test folder (without the intelligence of odoo-test-helper about registry).

This could be integrated simply in odoo.cfg file, in oca-ci images for instance (as some modules depends on the Odoo version).


What do you think of ?

**Comment by simahawk** [comment]
I would prefer to filter out the specific path. We can maintain a curated and documented list, starting with `["odoo.addons.mail.tests.test_mail_model.MailTest", ]`.

All in all it's a warning it shouldn't block your CI. This way we don't have to maintain a separated config.
My $0.02 :wink:

**Comment by rousseldenis** [comment]
> I would prefer to filter out the specific path. We can maintain a curated and documented list, starting with `["odoo.addons.mail.tests.test_mail_model.MailTest", ]`.

Yes, that was my first idea. The problem is that modules causing that are changing between versions (mail in 10.0, resource in 14.0, ...)

**Comment by simahawk** [comment]
> > I would prefer to filter out the specific path. We can maintain a curated and documented list, starting with `["odoo.addons.mail.tests.test_mail_model.MailTest", ]`.
> 
> Yes, that was my first idea. The problem is that modules causing that are changing between versions (mail in 10.0, resource in 14.0, ...)

Well, we know the odoo version. We can have a mapping instead of a simple list. Eg:
```
WHITELIST = {
    "14.0": ["odoo.addons.mail.tests.test_mail_model.MailTest", ],
    "10.0": ["odoo.addons.whatever.tests.test_foo.TestModel", ]
}
```
Old versions won't change, for new versions the effort would be the same.
N'est pas? :)

**Comment by rousseldenis** [comment]
> WHITELIST = {
>     "14.0": ["odoo.addons.mail.tests.test_mail_model.MailTest", ],
>     "10.0": ["odoo.addons.whatever.tests.test_foo.TestModel", ]
> }
> ```

Less intrusive. I like it. I'll change this accordingly

**Comment by rousseldenis** [comment]
@simahawk Done

**Review by simahawk — APPROVED** [review]
LG

**Comment by simahawk** [comment]
Available on 2.1.0 https://pypi.org/project/odoo-test-helper/2.1.0/

**Pull request merged**
